// Auto-generated by 5.publish.ts — do not edit manually.
// Re-run the publish script to regenerate after adding new courses.
const index = {
  slugs: [
    'alpine-golf-club',
    'krungthep-kreetha-sports-club',
    'lam-luk-ka-country-club',
    'nikanti-golf-club',
    'panya-indra-golf-club',
    'phoenix-gold-golf-country-club',
    'royal-gems-golf-sports-club',
    'summit-windmill-golf-club',
    'suwan-golf-country-club',
    'thai-country-club',
    'thana-city-golf-sports-club',
  ],
}

export default index
