// Auto-generated by 5.publish.ts — do not edit manually.
// Re-run the publish script to regenerate after adding new courses.
const index = {
  slugs: [
    'alpine-golf-resort-chiang-mai',
    'chiangmai-highlands-golf',
    'chiangmai-inthanon-golf',
    'gassan-khuntan-golf-resort',
    'gassan-lake-city-golf-club',
    'gassan-panorama-golf-club',
    'hang-dong-golf-club',
    'lanna-golf-course',
    'mae-jo-golf-club',
    'north-hill-chiang-mai',
    'royal-chiang-mai-golf-club',
    'summit-green-valley-chiangmai',
  ],
}

export default index
