// Auto-generated by 5.publish.ts — do not edit manually.
// Re-run the publish script to regenerate after adding new courses.
const index = {
  slugs: [
    'alpine-golf-resort-chiang-mai',
    'chiangmai-highlands-golf',
  ],
}

export default index
