// Auto-generated by 5.publish.ts — do not edit manually.
// Re-run the publish script to regenerate after adding new courses.
const index = {
  slugs: [
    'amata-spring-country-club',
    'burapha-golf-club',
    'chee-chan-golf-resort',
    'laem-chabang-international',
    'siam-country-club-old-course',
    'siam-country-club-plantation',
  ],
}

export default index
