// Auto-generated by 5.publish.ts — do not edit manually.
// Re-run the publish script to regenerate after adding new courses.
const index = {
  slugs: [
    // Phase 1
    'black-mountain-golf-club',
    'majestic-creek-country-club',
    'palm-hills-golf-club',
    'pineapple-valley-golf-club',
    'springfield-royal-country-club',
    // Phase 2 — Batch 1
    'kaeng-krachan-country-club',
    'korea-golf-club-hua-hin',
    'lake-view-resort-golf-club',
    'royal-hua-hin-golf-course',
    'sawang-resort-golf-course',
    'sea-pines-golf-resort',
  ],
}

export default index
