// Auto-generated by 5.publish.ts — do not edit manually.
// Re-run the publish script to regenerate after adding new courses.
const index = {
  slugs: [
    // Phase 1
    'blue-canyon-canyon-course',
    'blue-canyon-lakes-course',
    'laguna-golf-phuket',
    'loch-palm-golf-club',
    'red-mountain-golf-club',
    // Phase 2
    'aquella-golf-country-club',
    'mission-hills-phuket',
    'phuket-country-club',
  ],
}

export default index
